### PR TITLE
feat: otp via phone

### LINKED ISSUE #61: Add Send OTP via phone
Current implementation allows to send OTP only via SMS. Some numbers appears to be blacklisted and are not receiving the OTP message. 

So send OTP via Phone should be added

### PR DESCRIPTION
**Pull request by DarkPhoenix2704**
Current implementation allows to send OTP only via SMS. This add functionality to send OTP via VOICE

Closes #61

### CODE REVIEW

**Comment by akhilmhdh** [comment]
Hey @DarkPhoenix2704 

Kindly share the documentation from where u have refereed to implement this. If by default there is a voice template by msg91 team. Then we can drop all those env just give support as it is.

**Comment by DarkPhoenix2704** [comment]
https://docs.msg91.com/reference/send-voice-sms

You can find the documentation here.
The template has to be created

**Comment by akhilmhdh** [comment]
@DarkPhoenix2704 If voice template is needed then I am blocking this PR from merging as those things need to be setuped. Ill get back to this after discussed with @appukurian

**Comment by rohittp0** [comment]
No longer relavent

**Pull request closed without merging**
